      implicit real*8 (a-h,o-z)

      PARAMETER (IBAR2=   43, JBAR2=   82, NPRTS=1, MESHX=1, MESHY=1,
     1           NVOR=IBAR2*JBAR2*1.1/2, NTOB = 1)
      PARAMETER (MSHX=MESHX+1, MSHY=MESHY+1, NJF = JBAR2-2)
C
      COMMON /FV/ UN(IBAR2,JBAR2), VN(IBAR2,JBAR2), PN(IBAR2,JBAR2),
     1 FN(IBAR2,JBAR2), U(IBAR2,JBAR2), V(IBAR2,JBAR2), P(IBAR2,JBAR2),
     2 F(IBAR2,JBAR2), PETA(IBAR2,JBAR2), BETA(IBAR2,JBAR2),
     3 DTANTH(IBAR2,JBAR2), PS(IBAR2,JBAR2), NF(IBAR2,JBAR2), Fbar(NJF)
C
      COMMON /ME/ X(IBAR2), XI(IBAR2), RXI(IBAR2), DELX(IBAR2),
     1 RDX(IBAR2), RX(IBAR2), Y(JBAR2), YJ(JBAR2), RYJ(JBAR2),
     2 DELY(JBAR2), RDY(JBAR2), XL(MSHX), XC(MESHX), DXMN(MESHX),
     3 NXL(MESHX), NXR(MESHX), YL(MSHY), YC(MESHY), DYMN(MESHY),
     4 NYL(MESHY), NYR(MESHY)
C
      COMMON /PV/ XP(NPRTS), YP(NPRTS), VOL(NVOR), PR(NVOR), IP(NPRTS),
     1 JP(NPRTS), NR(NVOR)
C
      COMMON /IV/ IBAR, JBAR, IMAX, JMAX, IM1, JM1, IM2, JM2, NKX, NKY,
     1 iCYCLE,
     2 NMAT, NVRM, NREG,
     3 ISURF10, ICYL,
     4 IWL, IWR, IWB, IWT, NP, ITER, NOCON,
     5 NFLGC, ISYMPLT, IMOVY,
     6 NPX, NPY, IPL, IPR, JPB, JPT,
     7 NONUNIF, ISHVEL

      COMMON /FIV/ DELT, T, AUTOT, PRTDT, TWPRT, PLTDT, TWPLT, TWFIN,
     1 FLHT, VNU, CSQ, RCSQ, RHOF, RHOFC, RHOD, VCHGT, RDTEXP,
     2 SIGMA, CANGLE, DTANCA, CYL, GX, GY, UI, VI, OMG,
     3 ALPHA, EPSI, FLG, FLGC, FNOC,
     4 VELMX, VELMX1, XSHFT, YSHFT, XMIN, XMAX,
     5 YMIN, YMAX, SF, XPL, XPR, YPB, YPT,
     6 DTVIS, DTSFT, VORIG, SHVEL, VNUC
C

